//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Person
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class KHKAnsprechpartner
    {
        
        public int Nummer { get; set; }
        public short Mandant { get; set; }
        public int Adresse { get; set; }
        public string Ansprechpartner { get; set; }
        public string Gruppe { get; set; }
        public string Titel { get; set; }
        public string Vorname { get; set; }
        public string Nachname { get; set; }
        public string Position { get; set; }
        public string Abteilung { get; set; }
        public string Anrede { get; set; }
        public string Briefanrede { get; set; }
        public string ZuHaendenText { get; set; }
        public string Telefon { get; set; }
        public string Telefax { get; set; }
        public string Mobilfunk { get; set; }
        public string TelefonPrivat { get; set; }
        public string Autotelefon { get; set; }
        public string EMail { get; set; }
        public Nullable<System.DateTime> Geburtsdatum { get; set; }
        public string Memo { get; set; }
        public string Transferadresse { get; set; }
        public byte[] Timestamp { get; set; }
    }
}
